AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'lib/edir/parser.rb'
    - 'lib/edir/parser.y'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
