AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'lib/edir/204.tab.rb'
    - 'lib/edir/204.y'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
