#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

require './lexer'

class EdirParser
  def initialize
    @yydebug = true
  end
end

class EdirParser < Racc::Parser

module_eval(<<'...end 204.y/module_eval...', '204.y', 23)
def parse(str)
  @q = Edir::Lexer.new.lex_str(str)
  do_parse
end

def next_token
  @q.shift
end
...end 204.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    10,     5,     6,     5,     6,     5,     6,     2,     3,     7 ]

racc_action_check = [
     6,     6,     6,     2,     2,     5,     5,     0,     1,     3 ]

racc_action_pointer = [
     5,     8,    -1,     9,   nil,     1,    -3,   nil,   nil,   nil,
   nil ]

racc_action_default = [
    -5,    -5,    -5,    -5,    -1,    -5,    -5,    11,    -2,    -3,
    -4 ]

racc_goto_table = [
     4,     1,   nil,     8,     9 ]

racc_goto_check = [
     2,     1,   nil,     2,     2 ]

racc_goto_pointer = [
   nil,     1,    -2 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 7, :_reduce_1,
  2, 8, :_reduce_2,
  2, 8, :_reduce_3,
  2, 8, :_reduce_4 ]

racc_reduce_n = 5

racc_shift_n = 11

racc_token_table = {
  false => 0,
  :error => 1,
  :SEGSTART => 2,
  :SEGEND => 3,
  :ELEMSEP => 4,
  :ELEM => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SEGSTART",
  "SEGEND",
  "ELEMSEP",
  "ELEM",
  "$start",
  "segment",
  "elems" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', '204.y', 6)
  def _reduce_1(val, _values, result)
     return { segstart: val[0], elems: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', '204.y', 7)
  def _reduce_2(val, _values, result)
     return { elemsep: val[0], elems: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', '204.y', 8)
  def _reduce_3(val, _values, result)
     return { elemsep: val[0], elems: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', '204.y', 9)
  def _reduce_4(val, _values, result)
     return { elem: val[0], segend: val[1] }
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class EdirParser
